### ISSUE TITLE
missing required architecture x86_64

### ISSUE THREAD

**Issue by dburr** [SmileSoftware/TextExpanderTouchSDK#15]
Just tried building with the TextExpander SDK 3.5.4. I can build and run on an actual device but not the simulator. I get the following error when attempting to run on the simulator:

```
ld: warning: ignoring file /Users/dburr/Developer/iOS/_TestProjects/TETest/Pods/TextExpander/TextExpander.framework/TextExpander, missing required architecture x86_64 in file /Users/dburr/Developer/iOS/_TestProjects/TETest/Pods/TextExpander/TextExpander.framework/TextExpander (2 slices)
```

Am I doing something wrong?

**Comment by gscown** [comment]
For the Simulator, you'll need to rename TextExpander.framework.fat to TextExpander.framework and use that. The TextExpander.framework includes armv7 and arm64 and Bitcode for each. If we also include x86, the linker will strip Bitcode from your entire built result with no warning.

**Comment by youens** [comment]
I suppose that makes sense, but I will say it's fairly inconvenient that the default case prevents my app from running in the simulator. (Especially when using Cocoapods, where I can't easily mess with the files.) Or am I missing something here?

**Comment by dlo** [comment]
What @youens said...this seems really inconvenient.
