### ISSUE TITLE
TextExpanderTouchSDK fails on iOS 7 devices

### ISSUE THREAD

**Issue by rmaddy** [SmileSoftware/TextExpanderTouchSDK#16]
It seems that version 3.0 or later broke compatibility with iOS 7 due to the use of the class `NSFileAccessIntent`.

I was using version 2.3.1 just fine. Now when trying to use version 3.5 or 3.5.4, my app won't run on iOS 7 devices. I get a dylib error about `NSFileAccessIntent` which was added in iOS 8.0.

I'm trying to get an update for iOS 9 out but I my app's Deployment Target is iOS 7.0. It seems I can keep using TE 2.3.1 but I'd like to use the latest version (3.5.4).

Please update TextExpander so it avoids referencing `NSFileAccessIntent` (or any other iOS 8 classes) under iOS 7.x.

Thanks

**Comment by gscown** [comment]
Thank you for your feedback. iOS 7 compatibility is not a goal of the most current release of the TextExpander touch SDK. As you note, that is available through older releases if you wish. The TextExpander touch SDK 3.5 and later requires iOS 8.
