### ISSUE TITLE
Make framework dynamic

### ISSUE THREAD

**Issue by macguru** [SmileSoftware/TextExpanderTouchSDK#20]
Hey there,

as far as I can tell, the TE framework is currently a static framework. The issue is, that this means it's statically liked into the host binary. This works in most cases, but not when the library must be used from both a framework and an app. The current options are:

- Linking against both, but this causes duplicate class warnings as runtime
- Linking only the framework, adding just to search paths in host app. Causes Autolinker warning at built time
- Same as above, but remove module map from framework – disables auto linking but requires customizing the framework

Ideally, you would offer TE also as dynamic framework.

Thanks, Max

**Comment by gscown** [comment]
Thanks for the request. We expect to do a summer update of the TextExpander SDK. We'll take this into consideration for that update.

**Comment by gscown** [comment]
TextExpander is now offered as a dynamic framework in version 4.5, published moments ago.
