### ISSUE TITLE
Cannot Build App For iOS Simulator On Apple Silicon

### ISSUE THREAD

**Issue by fluecke** [SmileSoftware/TextExpanderTouchSDK#22]
Hey there!

Linking currently fails on Apple Silicon for any app linking against the TextExpander Touch SDK when building for iOS simulator:
```
ld: building for iOS Simulator, but linking in object file built for iOS, file '…/TextExpanderTouchSDK/TextExpander.framework/TextExpander' for architecture arm64
```

Are there any plans to update the SDK for Apple Silicon compatibility?

Thanks!

**Comment by gscown** [comment]
I believe we can solve this with an xcframework built with arm64 for iOS and both x86_64 and arm64 for iOS Simulator. Here's a try at that:

https://smilesoftware.com/downloads/test/2021-01-12-TextExpander.xcframework.zip

Feedback welcome.

**Comment by fluecke** [comment]
The xcframework works for me. Thanks for your help!
